---
- name: Install base software
  apt: name={{ item }}
       update_cache=yes
  with_items:
    - gcc
    - python
    - python-apt
    - python-dev
    - python-openssl
    - python-virtualenv
    - python-setuptools
    - unzip
