---
- hosts: all
  # remote_user: ubuntu
  become: True
  become_method: sudo
  become_user: root
  gather_facts: no
  vars:
    web2py_dir: /opt/web2py
    owner: www-data
  roles:
    - base
    - nginx
    - { role: letsencrypt, when: letsencrypt == True }
    - virtualenv
    - web2py
    - uwsgi
