---
- name: Install supervisor
  apt: name=supervisor
       update_cache=yes
  notify: restart supervisor

- name: Copy scheduler
  template: src=scheduler.conf
            dest=/etc/supervisor/conf.d/
  notify: restart supervisor
