---
- name: Install supervisor
  apt: name=supervisor
       update_cache=yes
  notify: restart supervisor

- name: Create log folder for app
  file: path={{ log_folder }}
        state=directory

- name: Copy scheduler
  template: src=scheduler.conf
            dest=/etc/supervisor/conf.d/
  notify: restart supervisorctl
