---
- name: Install footy module
  pip: name=footylib
       version={{ version }}
       virtualenv={{ web2py_dir }}_env

- name: Fix virtualenv permissions
  file: path={{ web2py_dir }}_env
        owner={{ owner }}
        group={{ owner }}
        state=directory
        recurse=yes
 