---
- name: Install pip
  easy_install: name=pip
                virtualenv={{ web2py_dir }}_env

- name: Install virtualenv
  pip: name=virtualenv

- name: Install footy module
  pip: name=footylib
       state=latest
       virtualenv={{ web2py_dir }}_env

- name: Fix virtualenv permissions
  file: path={{ web2py_dir }}_env
        owner={{ owner }}
        group={{ owner }}
        state=directory
        recurse=yes
