---
- name: Clone web2py
  git: repo=https://github.com/web2py/web2py.git
       dest={{ web2py_dir }}
       version={{ version }}
       track_submodules=yes

- name : Fix web2py permissions
  file: path={{ web2py_dir }}
        directory_mode=yes
        recurse=yes
        owner={{ owner }}
        group={{ owner }}

- name: Copy uwsgi handler
  copy: src={{ web2py_dir }}/handlers/wsgihandler.py
        dest={{ web2py_dir }}
        remote_src=True
        owner={{ owner }}
        group={{ owner }}
  notify: restart uwsgi
